name: OpenSSF Scorecard
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@2a2dd30f8030072d379eb0c9ea51789aa2ea9ca4
        with:
          sarif_file: results.sarif
        if: always()
